### ISSUE TITLE
[ask] optimizing artie transfer for faster data processing because of consumer lag

### ISSUE THREAD

**Issue by kholisrag** [artie-labs/transfer#994]
Hi, wanna ask about how to configure artie transfer to minimize the consumer lag in kafka

I already increase the resources request and limit to :

```yaml
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
```

but seem its not utilized fully.... below is the `top` of a 

```log
artie-transfer-dev-server-01-example1store-768f967fd-57qwk         118m         59Mi
artie-transfer-dev-server-01-example1store-768f967fd-cbcx4         41m          65Mi
```

this is the lag graph
![2024-10-31_11-32](https://github.com/user-attachments/assets/f1c9e443-7338-4424-9ccf-e14bf074a324)

any idea or advice? maybe configuration option that can be tweaked? 
Thanks in Advance
